CREATE USER IF NOT EXISTS auth_user WITH PASSWORD '1234';
ALTER USER auth_user WITH CREATEDB;
CREATE DATABASE IF NOT EXISTS auth_db OWNER auth_user;
GRANT ALL PRIVILEGES ON DATABASE auth_db TO auth_user;
